version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Glob19Ast35XX$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - banco-net

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - banco-net

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - banco-net

  account-service:
    build: .
    container_name: account-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://localhost:1433;databaseName=Bancos;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Glob19Ast35XX$
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - sqlserver
      - kafka
    networks:
      - banco-net

networks:
  banco-net:
    driver: bridge
